### ISSUE TITLE
[Question] Any interest in enhancements targeting images generated elsewhere, using models NOT stored locally?

### ISSUE THREAD

**Issue by norville101** [RupertAvery/DiffusionToolkit#181]
I don't generate images using my local machine, but rather I use a variety of online services to generate images:  StarryAI, DezGo, HappyAccidents, Civitai, Mage, and others.  Some of these services allow you to download images with metadata embedded (in various ways), and others do not.

Because of this angle, my first task was to actually **capture** the appropriate metadata and **embed** it into the images I downloaded.  For this purpose I started a different project -- it captures metadata from the site (typically using that site's API somehow, depending on the site) and *translates* that metadata into Automatic1111-compatible metadata, which it then embeds into the image. It works great for capturing and normalizing metadata among images originating with different services. (I have not yet published it on Github, because... it's a little complicated to use, depending on the service. And so I guess one question is, does anybody else want such a thing? Should I publish what I've got?  keeping in mind that some of the site integrations are more fully developed than others... but it's a good framework for working with and manipulating embedded metadata in png, webp, and jpeg formats).

So anyway... at this point I have many thousands of images, all with embedded A1111-style metadata, and I started trying to search and catalog and organize them.  So now I find DiffusionToolkit, which has been GREAT. The only catch is, its "models" features are designed to work with models available locally in an installation of A1111, which I do not have.  In fact, I'm not 100% sure how all the models features are intended to work, because not having any models locally prevents me from really playing with it or exploring it.

I've been slowly learning my way around DiffusionToolkit's code for a couple months now (in what little spare time I have), and I can see a couple ways to enhance it and make it work the way I would like it to with models, considering that the models I'M trying to work with are _not local_ and thus I do not always know the correct hash values for them. But I would still like to...

* easily see a list of all the model names (such as were extracted from metadata) that have been used to produce images in my library
* quickly browse through the images produced via each model (name)
* when looking at any image, easily jump to all the other images produced using the same (named) model

It's trivial to do a query in SQLite and get the list of all unique model names captured in the initial metadata scan... but my question is, what do you all think about this?  Does it seem like a good enhancement (something I should work on and submit a pull request for), or no?  Are there things I should keep in mind, to avoid messing with the "models" feature for people who ARE using it with Automatic1111 or other local image generation front-ends?

**Comment by RupertAvery** [comment]
The local models path thing is really just to load the model hashes and model names, and was used because that was the only way to get hashes and model names.  Then the A1111 cache.json came along, and now I have CivitAI integration to load models. 

I think there are people who would want to have the ability to integrate with online services. I don't use them so I never really had the need to integrate.

There are features in DiffusionToolkit that aren't really fully developed. Models, Prompts viewer, Folders.  They are just ideas that I started just as a way to explore it.  The Models page was initially to see model metata the way CivitAI does, and also view images related perhaps.

One thing holding me back is that there is a lot of code involved with the thumbnails view, and I don't want to replicate it between pages. As such the Prompts page is very basic, and just an attempt to see how prompts search and related images would work, and I'm not really too happy about it.

Adding a models selector like Albums would probably be really easy. I'll think of some ways to get what you need. You can probably get a list of model names and hashes using the Edit >Download models from CivitAI, and hopefully this will get you model names.  But I guess there may be a need to load model names manually from somewhere.

**Comment by norville101** [comment]
I guess the thing is, for users generating their own images locally against a1111 or comfyui or whatever, "models" is a very concrete thing -- a (big) file on your disk, that you're accustomed to managing.  For users using other services to generate images, "models" is necessarily a little more abstract, because they're usually NOT dealing with the actual model files.

So maybe you misunderstood... when I said "easily see a list of all the model names", I meant a list of "all the model names that are in the metadata of the images I have already loaded".  It's model names that you **already** have in the database, they don't need to be brought in from anywhere!  I imagine using these model names sort of like virtual or "smart" albums, automatically -- like I can see a list of each "model name" that any image purported to be generated by, and clicking that model name, I can see ALL the images that purport to be generated by that same model.

It's not perfect, nor is it fool-proof -- after all, some images may not have a "Model:" specified in their parameters, and the string that comes after "Model:" is not a strongly unique identifier (like a hash), leading to potential confusions -- but it would be a lot more useful than nothing!  (IMO.)

In the first instance, I had considered just changing the "Model Name" TextBox in the search window...

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/148023393/608825c2-eb55-44cd-bc4f-43d725c733c3)

... into a ComboBox. The TextBox portion would still be bound same as it is now, but the (dropdown) Items would be bound to the result of the following SQL query:  `select distinct Model from Image where Model not null`. The idea being, you could still type whatever you wanted into the box, but you would also have the option of easily seeing what models had been used to generate all the images in the database.

Does that make sense?  I'm just playing around with ideas too.

**Comment by RupertAvery** [comment]
So, a lot of images may not have a model name to search on, as it wasn't considered a mandatory field. In A1111 its shoved in with the "other" metadata (seed, cfg  ...) and ir can be turned on/off I think, javent checked lately.

So a lot of images only had the hash, and at times it was the old, incorrect hash.

So to be able to search for model "names" at all, I need to pull in the filename/hash pair from somewhere.

So when a user searches for a model by name, I search for the model name as a separate field, but I also try to do a lookup in the list of models I have found, and convert the model name to a matching hash, in case there are images lacking the model name field, but have a hash.

Perhaps now most images generated actually have model names embedded, along with correct hashes.

I understand what you want. I already implemented something like albums that shows you all the unique modelnames found in images, but also modelnames looked via hash from other sources in case the image doesn't have a model name.

I can also change that field to a drop down that lists all model names found in yoir images.

**Comment by RupertAvery** [comment]
See if this has what you need (Filter > Models > drop down with model names from images)

[Diffusion.Toolkit.v1.6 beta.zip](https://github.com/RupertAvery/DiffusionToolkit/files/13929696/Diffusion.Toolkit.v1.6.beta.zip)

**Comment by danrazor** [comment]
Dear Champs, kindly do a collab. 
you guys are just the right people with right mind doing the right thing.
historically, in the future, people would remember these conversations as they would for start of Photoshop or any other now famous tool.

what i find useful : 

1-mounting Root folder and (subfolders automatically get added) (minus the system volume folder or recycler)

2-thumbnail view and prompt view lead to image viewer and to real files in explorer.
(right now, the explorer thing is broken, it does not go to the image )

3. Prompt extensive search. advance search in the prompt and also (PLEASE) image describe! (where we input images without any PNGinfo and Ai reads the image and generate the prompt for the image.

4. information.
PROMPT: this is the most important thing. 
seed: 
Model name: (human readable names) (not like EMS-3432432-ems)
CFG:
sampler etc: (dpm - karas etc)
date of the generation (this is important and normally it is not identified in the PNG info)
the date is helpful because it reveals the historical AI system upgraded abilities.

anything or any information that help us understand how that image was made and help us recreate that same image anywhere.

I have used this information to almost exactly replicate images generated between different web services.
so that is helpful.
-------------------------
cheers

**Comment by norville101** [comment]
@RupertAvery ... sorry for my slow response, my day job often takes over my life for big periods. But yes, that is exactly what I was thinking... excellent.  Thanks!  That makes it a lot easier to search based whatever model name may have been embedded in the metadata. Awesome.
