### ISSUE TITLE
[BUG] 16.1 reports (Avira grabbed as threat DROP.WIN64.MemTaskProcess)

### ISSUE THREAD

**Issue by danrazor** [RupertAvery/DiffusionToolkit#220]
Hi, first hour usage report.
please review.

 1. IMPORTANT!!! FLAGGED and put in quarantine by antivirus. please check what kind of memory task the app intrude into the system that triggers the antivirus protocols?
 
 2. Tensor.Art Json data is still not recognized. 
 3. custom Hotkeys    (let us use keyboard shortcuts for hotkey usage)
 4. Prompt section is still not opening thumbnails to full screen or find in explorer or expand to folder.
 each section should have common system of usage. otherwise, what is the usage of the prompt section?
  
 I will report further soon.
 regards

Dan 
 
![image_2024-02-13_222328494](https://github.com/RupertAvery/DiffusionToolkit/assets/41794256/bb39abf4-46a0-4c69-a24e-2df45aff3014)

**Comment by RupertAvery** [comment]
1. It would be great if you could report this to Avira as I am sure I don't do any memory modification. I can't spend all the time trying to remedy antivirus issues when practically no other users have reported it. I will not follow up on virus reports.

2. I have to fix and implement things one at a time.  Please be patient.

3. This is not a priority for me. I would like to focus on functionality and bugs before other things. Realize that everything takes time, and this is just a hobby for me. It takes A LOT of my time. I have a normal job, and other responsibilities.

4. Again, I'm working on this. There are a lot of features I would like to implement and I have to prioritize them. Please be patient.

It would be good if you could limit your language to reporting issues and requesting and not demanding features.

The purpose of creating an issue such as you did before for Tensor.Art is so that is can be talked about there and not repeatedly demanded in separate issues.

A lot of issues here have been sitting for months before I can prioritize them. 

Please be patient.

**Comment by danrazor** [comment]
ChatGPT
"drop.win64.memtaskprocess" is a detection name used by Avira antivirus software to identify a potentially malicious file or behavior related to memory manipulation or exploitation on the Windows 64-bit platform.

When Avira flags an app with this detection name, it means that it has detected suspicious behavior or characteristics in the app that could indicate a threat to the security of your system. This could include actions such as attempting to access sensitive system resources, modifying system memory, or executing code in a suspicious manner.

**Comment by RupertAvery** [comment]
Does this have the same issue?

https://github.com/RupertAvery/DiffusionToolkit/actions/runs/7886310992/artifacts/1241357022

**Comment by danrazor** [comment]
using the link above,
so far so good.
nothing to report yet.

apologies if i sounded rushing. just excited. and wanted to help.

take your time.
Cheers.
