### ISSUE TITLE
[BUG] Metadata from StableSwarm is not read correctly

### ISSUE THREAD

**Issue by Mohsyn** [RupertAvery/DiffusionToolkit#250]
Metadata from Images created with StableSwarm are not read correctly and replaced with gibberish.

**Comment by RupertAvery** [comment]
Please provide some sample images so that I may investigate.

**Comment by Mohsyn** [comment]
![2036-ferro fluid, oil on water, dark opal in -OfficialStableDiffusionsd_xl_base_10s-361317289](https://github.com/RupertAvery/DiffusionToolkit/assets/51590078/db220b95-5716-43e0-9db5-29c8cd186e4f)
![0754-cinematic film still, close up, photo of-sdxlmainsdxlTurbosdxlTurbo_sdxlTurboP-3346112079](https://github.com/RupertAvery/DiffusionToolkit/assets/51590078/4bc1ebcf-6edb-4545-92e5-ff2fc4f7cfb2)

**Comment by RupertAvery** [comment]
It was caused by an issue in an external library (MetadataExtractor), reading the EXIF as big-endian, causing the encoding to be incorrect. After making modifications to the external library and then adding support to read the json metadata it is supported now.

![image](https://github.com/RupertAvery/DiffusionToolkit/assets/1910659/db003f55-1ca2-4391-9241-1572a453f880)

**Comment by Mohsyn** [comment]
Thanks
