### ISSUE TITLE
Update hash to support new AUTOMATIC1111 hash method

### ISSUE THREAD

**Issue by konqiDAM** [RupertAvery/DiffusionToolkit#53]
thats is
![imagen](https://user-images.githubusercontent.com/44301655/212551330-5bc91daa-29fc-4700-aff9-5844879543f9.png)

It never shows for me now the model name

**Comment by RupertAvery** [comment]
Did you set the model root path in Settings?

**Comment by konqiDAM** [comment]
http://sprunge.us/qs6LdB

**Comment by RupertAvery** [comment]
Can you attach the picture here if it's OK?  Is it only certain images that this happens?

**Comment by konqiDAM** [comment]
Not sure what picture do you mean, like full app screenshoot?
I noticed it doesn't print the correct information on any picture/model.

**Comment by konqiDAM** [comment]
I was checking again, more carefully, I'm not sure if something happened, but I think that maybe I figure it out, hashes of new images seem to be different. I took some screenshots, but 90% of what I do is NSFW. I noticed that one of the newer models that is not showing up now is actually showing up in an older image but with different hash. So something happened, but I don't know if its on A1111 side or what. Maybe it was updated ? 
If you want to take a look: https://imgur.com/a/lh55oHG but its all NSFW

**Comment by RupertAvery** [comment]
If you've updated A1111 recently, the hash are now different.  I haven't had the time to update A1111, so I haven't gotten around to looking at what's changed.

I'll update this issue to reflect the actual problem.

**Comment by RupertAvery** [comment]
AUTOMATIC1111 has switched to computing the full SHA-256 hash of the file that is calculated once when the model is first loaded. It is then cached to a cache.json file.

I have currently implemented this so that if you point Toolkit to the cache.json file, it will use the precomputed hashes. However, if you have not yet previously loaded the model in A1111's webui, the cached hash will not be there yet.

I found that hashing a 4GB/7GB in C# can be quite slow. Not minutes slow, but certainly slower than A1111, as it manages to use a 1MB buffer, whereas C#'s built-in hash only has a 4KB buffer. So A1111 is fast enough that it doesn't seem any different when switching models, plus it only does it when you select a model.

I don't know how this will affect non-A1111 users if those tools update their hash method as well.

Note that nothing has changed from the image metadata point of view. The hash seems to be a bit longer (10 characters instead of 8), but the same field is used.  DiffusionToolkit will still use the old hash method as a fallback.

You can still search using either hash.

It's just the display information that;s affected.

**Comment by RupertAvery** [comment]
I'm able to compute the hash now in comparable time, just needed to call some methods manually and use a large buffer. I am also able to write out the hashes in the same format used by AUTOMATIC1111 cache.json, however it seems that A1111 keeps a copy of the hashes in memory so if you try to update the cache outside the webui while it is running, A1111 doesn't know about it.

**Comment by RupertAvery** [comment]
This is now available in v0.9

* You have to set the path to A1111's cache.json in Settings > Checkpoints
* If you select a new model in A1111 who's SHA256 hash has not been calculated yet, A1111 will generate the new hash, but Toolkit needs to be refreshed to see the new hash. Click Edit > Reload Models to update the hash.
* Click on another image to update the hash in the preview pane
