### ISSUE TITLE
Option to Scan without Dialogue Box

### ISSUE THREAD

**Issue by Snowej** [RupertAvery/DiffusionToolkit#68]
Something simple. When you press the "Scan folders for new images" button, it'd be nice to have an option to disable the "Scan Complete" dialogue box that sates the scan is complete, rather than having to click it every time.

Would also be nice to have an option to update the library automatically, whether it's when a new image is generated or periodically.

And finally, a button to show your entire library. Something like "Show all" between "Search" and "Favourites" buttons.

Great app, many thanks.

**Comment by icefreez** [comment]
I agree, an option for a status field might be in the toolbar, or to take over the "# images in database" toolbar at the bottom.

**Comment by RupertAvery** [comment]
> Would also be nice to have an option to update the library automatically, whether it's when a new image is generated

The Watch Folders option in Settings under the General tab should already do this, but for some reason it stopped working for me recently.

I uses a system folder watch to watch for changes to a folder (and it's subfolders), and notify the app about the changes. The weird thing for me is that I noticed that when the change notification happens, it looks like some temp filename that doesn't have the extension I'm looking for, so the app ignores it.

I thought it might have something to do with my file copy manager, TeraCopy, but I haven't really tested this theory.

> And finally, a button to show your entire library. Something like "Show all" between "Search" and "Favourites" buttons.

I'm not sure what you mean.  The Search button basically shows everything if the query is blank.  I can set this to load initially.
It's difficult to load "everything" in one page, since users can have literally hundreds of thousands of images.  It's not practical to show this in one page, so I "page" the results.  It's possible to do virtualization, but I prefer paging.

**Comment by mattehicks** [comment]
YES! Get rid of the dialog boxes.

**Comment by RupertAvery** [comment]
I think it's still important to have some visible feedback to the user (status bar isn't such a great place for this), so a small semitransparent "toast" that goes away after 3 seconds or on click, that doesn't block user input is probably a good alternative.

![image](https://user-images.githubusercontent.com/1910659/232636023-6dcf636c-b15e-40cd-a1c2-a9c52adcfcdc.png)

**Comment by icefreez** [comment]
A popup toast would be fantastic!

**Comment by mattehicks** [comment]
Agree!

**Comment by RupertAvery** [comment]
Implemented, closing
