### ISSUE TITLE
Add Aesthetics Score to Thumbnail and Preview

### ISSUE THREAD

**Issue by R3dPhil** [RupertAvery/DiffusionToolkit#73]
Can you add the astetics score to the previews or am i missing someting i cant see in it but i can filter for it

**Comment by RupertAvery** [comment]
The aesthetic score appears in the line with seed, cfg, steps, etc, usually at the end.

![image](https://user-images.githubusercontent.com/1910659/232633956-b86f2bc8-6ede-4be1-9cc9-4479cac6e0f7.png)

I can probably add a bigger number somewhere, probably after the stars, at the risk of running out of space.

![image](https://user-images.githubusercontent.com/1910659/232634101-9255cdff-b6aa-4643-b777-b36a84768ceb.png)

I'm also adding it to the thumbnail view:

![image](https://user-images.githubusercontent.com/1910659/232634187-8dbdfe87-84e7-485b-b1a2-5ca175e3c174.png)

**Comment by RupertAvery** [comment]
Done

**Comment by sean1138** [comment]
it shows at the end of my pnginfo but as "Score" not "aesthetic_score" and it doesn't show at all it diffusion toolkit info - something i'm doing wrong?
![image](https://user-images.githubusercontent.com/6720184/233787057-58fd9f77-85e0-47bd-afc7-d1f5b681f8f6.png)
![image](https://user-images.githubusercontent.com/6720184/233787136-6bdba08a-84a9-41ae-b1de-6838750c4c5b.png)

i'm using this, do i need to use a different thing?
https://github.com/vladmandic/sd-extension-aesthetic-scorer

toolkit seems to be unable to find the model i'm using now in the info but i'm less bothered by that since it still shows the model hash.
