### ISSUE TITLE
Portable mode for database and config.json

### ISSUE THREAD

**Issue by NoSie** [RupertAvery/DiffusionToolkit#77]
Thanks for this very useful app!
It would be helpful if the location location of the database and config.json were not hardcodes to %APPDATA% so that all files/info could be held in a single folder, e.g. on a portable device.

**Comment by RupertAvery** [comment]
Portable mode has been added and will be available in the next release.

For convenience, there is a checkbox in settings that, once clicked, will attempt to copy your config and database from app settings (local) to your exe location (portable). Unchecked, and will will do the reverse. I try as much as possible to avoid accidentally overwriting files, so there are checks and dialog boxes asking for confirmation.

The gist is that, if a config.json and diffusion-toolkit.db are found next to the exe, it will run in portable mode, otherwise it will look for the settings in %APPDATA%

**Comment by NoSie** [comment]
Perfect! Thank you very much!

**Comment by RupertAvery** [comment]
Implemented, closing
