### ISSUE TITLE
Make it searchable by file name or file path?

### ISSUE THREAD

**Issue by toshi-miura** [RupertAvery/DiffusionToolkit#8]
Thank you for always responding to issues.

If I actually want to search for a file, I'd like to do so at the prompt as well.
I also categorize by file or folder name.
I may want to search by file or folder name

Also, it would be great to be able to search for multi-bytes

**Comment by toyxyz** [comment]
I'm curious too. It would be nice to be able to filter by tab according to the folder. ~img2img, txt2img, txt2img-grid etc

**Comment by Neuralsplyce** [comment]
I am also interested in searching by filename since I often modify image filenames.

**Comment by RupertAvery** [comment]
> I am also interested in searching by filename since I often modify image filenames.

I'll need to add a rename feature, since if you rename the file outside the app, it will not know, and you'd have to rescan your files, causing any existing stuff like favorites and ratings (new features) to be lost on the old filename.

I can add a search by path.  Just need to consider how to use it.

for example, using glob:

```
path: "D:\stable diffusion\images\**" - starts with 
path: "**img2img**" - contains
```

I think SQLite supports GLOB internally, so this would be a good fit.

> Also, it would be great to be able to search for multi-bytes 

SQLite supports multi-byte characters natively, so it should work

**Comment by RupertAvery** [comment]
I also am thinking of a feature called Lists, like Playlists in Spotify, where you click on a song and Add to a playlist or create one.

Aside from that, I was also thinking of auto-lists, where you set a filter for a list and any matching images appear there.  This would work well with paths.
