### ISSUE TITLE
Add capability to search by model name using the query 

### ISSUE THREAD

**Issue by mattehicks** [RupertAvery/DiffusionToolkit#80]
I'd like to be able to search just by model name (or partial model name). 
I mean, really this should be one of the primary uses for Diffusion Toolkit, seems like an oversight.

I realize there is the 'advanced' filter method - but why not just incorporate into the main UI?
Let me know if there's any way I can help code this - just hit me with a starter on where to look.
Thanks!

**Comment by RupertAvery** [comment]
There are 2 things to this:

1)  A1111 and other tools don't embed the model name in metadata by default, and uses hashes to identify the model. So for a lot of users generated images don't contain the model name.

Right now the only way advanced filter works now is by doing a lookup on the A1111 cache, (partial) model name -> hash, of course this can be ported to the query search.

2) I would also need to start tracking if the model name is embedded in the metadata, and do an OR on hash vs model name.

For the case of 1, add model name to the query search, for example, using the format:

```
model_name: "<model name with spaces>"|<modelnamewithoutspaces>
```

Go to `Diffusion.Database` project and open up `QueryBuilder.cs`

You want to create a regex to parse the model name token from the query: e.g.

```
private static readonly Regex PathRegex = new Regex("\\bmodel_name:\\s*(?:\"(?<value>[^\"]+)\"|(?<value>\\S+))", RegexOptions.Compiled | RegexOptions.IgnoreCase);
```

The query parser works by matching some regex and removing it from the query to clean up the query so that the final query will contain just the prompt at the end (hopefully).

You create a  `ParseModelName(ref prompt, conditions)` method and call it from the `Parse(string prompt)` method.

The tricky thing about model name is that the names may come from the A1111 cache, so you need to inject that somehow into querybuilder. The Filter method gets away with this by preprocessing the model name into a hash.

Your ParseModelName method should add to the conditions a keyvaluepair that contains the clause that will be ANDed to the overall WHERE clause, which should contain a ? (question mark) that will be replaced by SQLite with the value of the KVP.

Suppose you do a lookup from model names to one or more hashes, you would probably need to buld a clause that does:

((ModelHash = ?) OR (ModelHash = ?)  OR (ModelHash = ?))

so you need to pass multiple values. DT supports "nested" conditions, so you can prolly do this:

e.g., 

```
           // hashConditions is an IEnumerable string that contains a "(ModelHash = ?)" for each matched hash.
            var hashOrs = string.Join(hashConditions, " OR ");
            // values is an IEnumerable<string> containing the matching hashes.
            conditions.Add(new KeyValuePair<string, object>($"({hashOrs})", values));
```

In the case of 2:

There currently is no field for model name.  Add a ModelName property to the Image class in  Difusion.Database.  

The field will be created in the database by the SQLite library on load, so you don't have to worry about creating a migration or something.

Also add a ModelName property to the FileParameters class in Diffusion.IO

In the DataStore.cs file add an index for ModelName

```
        db.CreateIndex<Image>(image => image.ModelName);
```

Then, the fun part. In Diffusion.IO.Metadata, update the parsers to read the model name from the metadata.  A1111 probably writes it as `Model Name: <...>` embedded with the Steps, CFG, etc

other metadata formats encode it differently, or not at all

Then in MainWindow.xaml.cs, go to the ScanFiles method, and look for the part that instantiates a new Image, and add the property there:


```
                 var image = new Image()
                    {
                        Prompt = file.Prompt,
                        NegativePrompt = file.NegativePrompt,
                        Path = file.Path,
                        Width = file.Width,
                        Height = file.Height,
                        ModelHash = file.ModelHash,
                        Steps = file.Steps,
                        Sampler = file.Sampler,
                        CFGScale = file.CFGScale,
                        Seed = file.Seed,
                        BatchPos = file.BatchPos,
                        BatchSize = file.BatchSize,
                        CreatedDate = File.GetCreationTime(file.Path),
                        AestheticScore = file.AestheticScore,
                        HyperNetwork = file.HyperNetwork,
                        HyperNetworkStrength = file.HyperNetworkStrength,
                        ClipSkip = file.ClipSkip,
                        FileSize = file.FileSize,
                        NoMetadata = file.NoMetadata,
                        ModelName = file.ModelName  <-- NEW PROPERTY
                    };
```

That should have you parsing the ModelName from an image and writing the ModelName to the database.

Now, go back to the QueryBuilder and add an "OR ModelName LIKE '%?%'" to your conditions.

There might be some stuff I missed, but that's the nitty gritty.

**Comment by RupertAvery** [comment]
Implemented, closing
